name: Publicar Pacote (Versão da C&D Sistemas)

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.NUGET_TOKEN }}
        env:
          NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
